### PR TITLE
Update datasets.yml

### PR DESCRIPTION
**Pull request by ppival**
Suggesting the addition of Twitter's election integrity data set. Seems unfair that **they** can publish the actual tweets, but I guess when you're the boss... ;-)

### CODE REVIEW

**Comment by edsu** [comment]
Downloading these datasets that Twitter published is somewhat non-trivial. So I worked with Mark Graham at Internet Archive to make them available there:

* https://archive.org/details/twitter-iran
* https://archive.org/details/twitter-ira

Do you think it might be better to publish two datasets in the docnow catalog that point there?

**Comment by ppival** [comment]
That certainly makes sense Ed, though that's still a lot of zip files to download (torrents aren't allowed on my campus). Off to make pull requests :-)

**Comment by edsu** [comment]
Yes, if you try to download the data from Twitter's website you end up having to also download a ton of zip files. The precarity of that was one of the reasons why we decided to put a copy at Internet Archive. The torrent is a convenient way of downloading, but it is often blocked. You can also use the [internetarchive command line tool](https://internetarchive.readthedocs.io/en/latest/cli.html#download) to download a collection, which is quite handy:

    % ia download twitter-iran

**Comment by edsu** [comment]
This was taken care of in #52

**Pull request closed without merging**
